sonar.projectKey=hello-world
sonar.projectName=Hello World Rails
sonar.sources=app,lib
sonar.exclusions=vendor/**,node_modules/**,db/**,log/**,tmp/**
sonar.ruby.coverage.reportPaths=coverage/.resultset.json
